---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_KEYPAIR'] %>
  region: <%= ENV['AWS_REGION'] %>
  security_group_ids: 
    - <%= ENV['AWS_SECURITY_GROUP_ID'] %>
  subnet_id: <%= ENV['AWS_SUBNET_ID'] %>
  vpc_id: <%= ENV['AWS_VPC_ID'] %>
  associate_public_ip: true
  instance_type: t2.micro
  tags:
    # Replace YOURNAME and YOURCOMPANY here
    Name: "Chef Training Node for <YOURNAME>, Rees"
    user: Administrator
    X-Contact: "Anthony Rees"
    X-Application: "apac"
    X-Dept: "sales"
    X-Customer: "Rees"
    X-Project: "BJC-Demo"
    X-TTL: 4

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 14.12.3

verifier:
  name: inspec
  format: documentation

platforms:
  - name: centos-6
    transport:
      username: centos
      ssh_key:  ~\.ssh\id_rsa
    driver_config:
      user_data: C:/Users/chef/user_data

suites:
  - name: default
    run_list:
      - recipe[webserver::default]
    verifier:
      inspec_tests:
      - test/integration/default
    attributes:
